export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_FAILURE = 'FETCH_DISHES_FAILURE';

export const SAVE_ORDER_REQUEST = 'SAVE_ORDER_REQUEST';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE';

export const ADD_DISH_TO_ODER = 'ADD_DISH_TO_ODER';
export const REMOVE_DISH_FROM_ODER = 'REMOVE_DISH_FROM_ODER';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const CLEAR_ORDER = 'CLEAR_ORDER';
